HOLOGRAM_LINE_1 = "&eDisfruta tu estancia"
HOLOGRAM_LINE_2 = "&bÂ¡Golpea a un NPC para unirte a un juego!"
HOLOGRAM_LINE_3 = "&eHay &a%s &ejugadores en la red"
HOLOGRAM_LINE_4 = "&eEstas en el hub"
HOLOGRAM_LINE_5 = "&aweb.clovercube.net
HOLOGRAM_LINE_6 = "&9CloverCube &cBETA"
HOLOGRAM_LINE_7 = "&bplay.clovercube.net"
MARKETPLACE_NPC_TAG_HEADER = "&l&cTienda"
MARKETPLACE_NPC_TAG_FOOTER = "&eClic para explorar"